[2023-12-18 14:05:48,350: INFO: main: welcome to custom logger:]
[2023-12-20 15:39:44,272: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-20 15:39:44,283: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-20 15:39:44,286: INFO: common: directory: artifacts created successfully:]
[2023-12-20 15:39:44,289: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-20 15:39:44,297: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1JfGoWzhbOJwLJgEs-bhXuIcjuz4F0-vE/view?usp=drive_link into file artifacts/data_ingestion/data.zip:]
[2023-12-20 15:40:18,390: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1JfGoWzhbOJwLJgEs-bhXuIcjuz4F0-vE/view?usp=drive_link into file artifacts/data_ingestion/data.zip:]
[2023-12-20 15:51:46,326: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-20 15:51:46,341: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-20 15:51:46,343: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-20 15:51:46,343: INFO: common: directory: artifacts created successfully:]
[2023-12-20 15:51:46,345: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-20 15:51:46,905: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 20 Dec 2023 20:51:47 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=511=cdntPkZFWGX4_t_cGnWcPykh_D22r1Qovf_ysatl8dquIBRppMTLxl-pnZvUkMb6YVzIyaol7SI4ZwImtHoZ7JWzvxCEAmbdyeiU7LTzAjV1eHbxwkAw0EctmPqdRnRbh8xruDDDu8SI4vMmO5Nmw1DmwONZW8u8snUaT0YUI-Y; expires=Thu, 20-Jun-2024 20:51:47 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

:]
[2023-12-20 15:51:47,216: ERROR: main: File is not a zip file:]
Traceback (most recent call last):
  File "d:/Kidney-Disease-Classification-DeepLearning-Project-MlFlow/main.py", line 11, in <module>
    data_ingestion.main()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-12-20 15:53:29,841: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-20 15:53:29,843: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-20 15:53:29,844: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-20 15:53:29,845: INFO: common: directory: artifacts created successfully:]
[2023-12-20 15:53:29,846: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-20 15:53:29,846: INFO: data_ingestion: File already exists of size: ~ 83 KB:]
[2023-12-20 15:53:29,847: ERROR: main: File is not a zip file:]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-12-20 15:54:30,401: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-20 15:54:30,404: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-20 15:54:30,405: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-20 15:54:30,406: INFO: common: directory: artifacts created successfully:]
[2023-12-20 15:54:30,407: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-20 15:54:30,409: INFO: data_ingestion: File already exists of size: ~ 83 KB:]
[2023-12-20 15:54:30,410: ERROR: main: File is not a zip file:]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-12-24 14:59:46,498: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-24 14:59:46,516: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-24 14:59:46,542: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-24 14:59:46,543: INFO: common: directory: artifacts created successfully:]
[2023-12-24 14:59:46,543: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-24 14:59:46,544: INFO: data_ingestion: File already exists of size: ~ 83 KB:]
[2023-12-24 14:59:46,722: ERROR: main: File is not a zip file:]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-12-24 15:02:21,160: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-24 15:02:21,168: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-24 15:02:21,169: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-24 15:02:21,169: INFO: common: directory: artifacts created successfully:]
[2023-12-24 15:02:21,170: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-24 15:02:22,534: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Sun, 24 Dec 2023 20:02:21 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=511=ZmZcfjXV93P3m4dRfosDyiH0PtG6lRBq0wPqxPnsvmM0JUxo0raiLJjc8u23F4syDmTpCMdD50qEv19oFZoKifiGJ_E5rVyyAAT8KMk53X0RSx8MWYGFE_zz-62Aii2Gsy_T69LchBpQSB_IngX7s0CYpaoEQVhEGPvBBDFIptQ; expires=Mon, 24-Jun-2024 20:02:21 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

:]
[2023-12-24 15:02:22,637: ERROR: main: File is not a zip file:]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-12-24 15:05:30,127: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-24 15:05:30,137: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-24 15:05:30,146: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-24 15:05:30,147: INFO: common: directory: artifacts created successfully:]
[2023-12-24 15:05:30,147: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-24 15:05:30,153: INFO: data_ingestion: File already exists of size: ~ 83 KB:]
[2023-12-24 15:05:30,168: ERROR: main: File is not a zip file:]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-12-24 15:05:35,501: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-24 15:05:35,503: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-24 15:05:35,504: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-24 15:05:35,505: INFO: common: directory: artifacts created successfully:]
[2023-12-24 15:05:35,505: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-24 15:05:35,506: INFO: data_ingestion: File already exists of size: ~ 83 KB:]
[2023-12-24 15:05:35,506: ERROR: main: File is not a zip file:]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-12-24 15:05:59,619: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-24 15:05:59,622: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-24 15:05:59,624: INFO: common: directory: artifacts created successfully:]
[2023-12-24 15:05:59,626: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-24 15:05:59,628: INFO: 986331348: Downloading data from https://drive.google.com/file/d/10bxwwkP1GCjwLxa29PmBqPdbXUdCk8Ch/view?usp=sharing into file artifacts/data_ingestion/data.zip:]
[2023-12-24 15:06:02,775: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/10bxwwkP1GCjwLxa29PmBqPdbXUdCk8Ch/view?usp=sharing into file artifacts/data_ingestion/data.zip:]
[2023-12-26 12:59:57,579: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-26 12:59:57,613: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-26 12:59:57,619: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-26 12:59:57,620: INFO: common: directory: artifacts created successfully:]
[2023-12-26 12:59:57,640: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-26 12:59:58,654: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Tue, 26 Dec 2023 17:59:56 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=511=mmLhDNpZOmXdO-zZ-qeafzCe86K3I_4adQMFwowubrrkRzxseE4E6llooRcMY_eyJUfxfHGZNQ6i1Y7kKd5BytpzL2hHn32qTW5HC4cGXtnM5v6KHubH-Lttz5jTKF9wHDkVmHMterDc5WYKXIPqTlY7ApfQjS5gRnQomcl8KIg; expires=Wed, 26-Jun-2024 17:59:56 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

:]
[2023-12-26 12:59:58,762: ERROR: main: File is not a zip file:]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    data_ingestion.main()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "d:\chicken-disease_endtoend_project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "D:\Software\Install\miniconda\envs\kidney\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2023-12-26 13:02:12,223: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-26 13:02:12,231: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-26 13:02:12,234: INFO: common: directory: artifacts created successfully:]
[2023-12-26 13:02:12,236: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-26 13:02:12,239: INFO: 986331348: Downloading data from https://drive.google.com/file/d/10bxwwkP1GCjwLxa29PmBqPdbXUdCk8Ch/view?usp=sharing into file artifacts/data_ingestion/data.zip:]
[2023-12-26 13:02:19,312: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/10bxwwkP1GCjwLxa29PmBqPdbXUdCk8Ch/view?usp=sharing into file artifacts/data_ingestion/data.zip:]
[2023-12-26 13:02:25,873: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-26 13:02:25,878: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-26 13:02:25,879: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-26 13:02:25,880: INFO: common: directory: artifacts created successfully:]
[2023-12-26 13:02:25,880: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-26 13:02:25,881: INFO: data_ingestion: File already exists of size: ~ 56361 KB:]
[2023-12-26 13:02:26,705: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2023-12-26 13:50:19,657: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-26 13:50:19,683: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-26 13:50:19,686: INFO: common: directory: artifacts created successfully:]
[2023-12-26 13:50:19,688: INFO: common: directory: artifacts/prepare_base_model created successfully:]
[2023-12-26 13:50:22,266: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2023-12-29 14:13:46,896: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-29 14:13:46,946: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-29 14:13:46,985: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-29 14:13:46,986: INFO: common: directory: artifacts created successfully:]
[2023-12-29 14:13:46,986: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-29 14:13:46,987: INFO: data_ingestion: File already exists of size: ~ 56361 KB:]
[2023-12-29 14:13:48,250: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2023-12-29 14:18:13,889: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-29 14:18:13,891: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-29 14:18:13,894: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-29 14:18:13,895: INFO: common: directory: artifacts created successfully:]
[2023-12-29 14:18:13,897: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-29 14:18:13,898: INFO: data_ingestion: File already exists of size: ~ 56361 KB:]
[2023-12-29 14:18:14,521: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2023-12-29 14:20:11,394: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-29 14:20:11,397: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-29 14:20:11,399: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-29 14:20:11,400: INFO: common: directory: artifacts created successfully:]
[2023-12-29 14:20:11,401: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-29 14:20:11,401: INFO: data_ingestion: File already exists of size: ~ 56361 KB:]
[2023-12-29 14:20:11,997: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2023-12-29 16:11:44,095: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2023-12-29 16:11:44,124: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-29 16:11:44,155: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-29 16:11:44,180: INFO: common: directory: artifacts created successfully:]
[2023-12-29 16:11:44,181: INFO: common: directory: artifacts/data_ingestion created successfully:]
[2023-12-29 16:11:44,182: INFO: data_ingestion: File already exists of size: ~ 56361 KB:]
[2023-12-29 16:11:45,072: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2023-12-29 16:11:45,073: INFO: main: *******************:]
[2023-12-29 16:11:45,073: INFO: main: >>>>>> stage Prepare base model started <<<<<<:]
[2023-12-29 16:11:45,076: INFO: common: yaml file: config\config.yaml loaded successfully:]
[2023-12-29 16:11:45,078: INFO: common: yaml file: params.yaml loaded successfully:]
[2023-12-29 16:11:45,079: INFO: common: directory: artifacts created successfully:]
[2023-12-29 16:11:45,080: INFO: common: directory: artifacts/prepare_base_model created successfully:]
[2023-12-29 16:11:50,158: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.:]
[2023-12-29 16:11:52,070: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x:]
